export const IPC = {
  ViewGet: 'view:get',
  HistorySelectItem: 'history:selectItem',
  HistoryPinItem: 'history:pinItem',
  HistoryDeleteItem: 'history:deleteItem',
  HistoryClearAll: 'history:clearAll',
  HistoryUpdateItemText: 'history:updateItemText',
  HistoryGetSize: 'history:getSize',
  HistoryChanged: 'history:changed',
  PopupHide: 'popup:hide',
  PopupConfirmHoldSelection: 'popup:confirmHoldSelection',
  BucketsSetCurrent: 'buckets:setCurrent',
  BucketsGetItems: 'buckets:getItems',
  BucketsCreate: 'buckets:create',
  BucketsRename: 'buckets:rename',
  BucketsDelete: 'buckets:delete',
  SettingsGet: 'settings:get',
  SettingsUpdate: 'settings:update',
  AppGetVersion: 'app:getVersion',
  AppGetPlatform: 'app:getPlatform'
} as const
